### ISSUE TITLE
No matching distribution found for mayavi==4.2.0

### ISSUE THREAD

**Issue by fjnn** [enthought/mayavi#1019]
Hello,
For a deprecated project, I need to use mayavi in Python2. When I compute `pip install mayavi==4.2.0` unfortunately I cannot compute such a command because it returns:
`Could not find a version that satisfies the requirement mayavi==4.2.0 (from versions: 4.3.1, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.7.0, 4.7.1, 4.7.2)`

I cannot build from source because as far as I see there is no available branch for this version. Is there any way to pip install mayavi for Python2?

**Comment by rahulporuri** [comment]
> When I compute `pip install mayavi==4.2.0` unfortunately

Just to be safe, when you run `pip` is that using the python 2 system python or python 3 system python or are you working in a virtual environment or ? If it's possible, you could use edm or conda to install the older version that you need - instead of relying on pip.

> I cannot build from source because as far as I see there is no available branch for this version. Is there any way to pip install mayavi for Python2?

There are no branches but there are tag. You can checkout the 4.2.0 tag https://github.com/enthought/mayavi/releases/tag/4.2.0 and build mayavi from source that way. I hope that solves your need.

I'm closing the issue for now. Please feel free to reopen it if you run into any other issue while installing the old version.
