### ISSUE TITLE
installing mayavi from source with VTK installed from souce

### ISSUE THREAD

**Issue by fred4ets** [enthought/mayavi#1023]
Hi all,

I've just installed VTK-9.0.1 from source.

All is ok, i can import vtk from ipython, for instance.

But when I want to install mayavi from git source, mayavi does not find VTK and download it (an old version) from pypi.org.

I noticed that vtk installed in /usr/local/lib/python3.7/dist-packages has no egg file, but a vtk.py file and a vtmodules/ dir.

Mayavi seems to not understand this.

So, I can fix it?

Should I install egg from VTK source?

But how can I do this?

Or is there another trick to make mayavi understand that VTK 9.0.1 is already installed?

Thanks in advance for any help.

OS : Debian 10 x86_64
Python 3.7
ETS source from git, VTK source from VTK.org

**Comment by rahulporuri** [comment]
Hey @fred4ets. I'm not too familiar with debian or what the difference between installing vtk from pypi vs installing vtk from source. It's possible that mayavi doesn't find vtk because it doesn't find the `.EGG_INFO` directory for vtk. We saw something similar happen on FreeBSD. Can you try this - https://github.com/enthought/mayavi/issues/1005#issuecomment-765280015 - and see what happens?

**Comment by fred4ets** [comment]
Hi,

Your trick runs fine ! :)

Thanks a lot !

Regards
