### ISSUE TITLE
Versions of python and vtk supported are unclear

### ISSUE THREAD

**Issue by Sbozzolo** [enthought/mayavi#1063]
The issue tracker is full of issues originating with problems with versions of vtk or python (eg, #939, #940). It is very confusing to understand which versions of the software are supported, and I couldn't find any indication about this in the documentation.

In my experience, somettimes mayavi works with vtk 9, other times it doesn't. For example, [here](https://github.com/Sbozzolo/kuibit/actions/runs/1086276816) I have a GitHub action in which it is not even possible to install mayavi on a fresh ubuntu-latest image with the latest vtk and python 3.8. Regardless, I didn't find a clear mention of whether vtk 9 is supposed to work or not.

**Comment by SunMesa** [comment]
Total newbie here, only commenting because I'm also unable to install mayavi 4.7.3 from a command window on Windows 7, in an environment of Python 3.8.10 and vtk 9.0.3, at least using the simple "py -m pip install mayavi" method. It shows a lengthy list of "Requirement already satisfied" for various packages it needs, and finally says "Building wheel for mayavi (setup.py) ... \". At which point it goes into limbo... never completes, never responds (I've let it run overnight).

**Comment by rahulporuri** [comment]
closing as mayavi now works as expected with all supported python and vtk versions.
