### ISSUE TITLE
Docs: Update the known bugs and issues list

### ISSUE THREAD

**Issue by jdmarch** [enthought/mayavi#181]
https://github.com/enthought/mayavi/blob/master/docs/source/mayavi/bugs.rst is 4 years out of date.

**Comment by itziakos** [comment]
There have been a number of updates and changes (e.g. move to vtk 6.2) in the last 4 years and it is not clear if these bugs or other bugs that are in github. To this extent I do not think that we can populate the bugs section reliably. I would suggest to replace the section with a link to github issues and slowly move through the back log and verify reported bugs.

**Comment by jdmarch** [comment]
Good point. On the other hand, precisely because github issues is unclear, that would not be very useful for most users. What about a middle ground -- have this doc enumerate/describe only the most active current issues, and refer to github issues for everything else?

**Comment by itziakos** [comment]
>  have this doc enumerate/describe only the most active current issues, 

I am not sure what is the advantage of such a list. In my mind the Known issues section contains those items that are big and important but are not active, because they need a lot of effort or there is no solution for them (e.g. http://doctrine-orm.readthedocs.org/en/latest/reference/limitations-and-known-issues.html#known-issues). For example, `known issues` would have been supporting VTK 6.2 or if we know that a specific graphics card is not working.

I guess we could add python 3 support as a known issue and Qt5. Would that be ok?

**Comment by itziakos** [comment]
initial work done in #229
