### ISSUE TITLE
Cropped text

### ISSUE THREAD

**Issue by davidcortesortuno** [enthought/mayavi#396]
When I use numbers within a `text`, it gets cropped. Here is a minimal working example:

```python
from mayavi import mlab
import numpy as np

data = np.random.random((3, 3))
f = mlab.figure(bgcolor=(1, 1, 1), fgcolor=(0, 0, 0), size=(500, 500))
mlab.points3d(data)

t = mlab.text(0.7, 0.9,
              '16',
              width=0.16,
              line_width=2.,
              )

mlab.show()
```

is this related to VTK? There is an old thread that addresses this issue http://www.vtk.org/pipermail/vtk-developers/2012-December/028033.html But it seems it is fixed in recent VTK versions http://www.vtk.org/Bug/view.php?id=13710

Here is a preview:

![image](https://cloud.githubusercontent.com/assets/12200541/16201528/b901ca8e-3709-11e6-9d12-8381d7222408.png)

If I increase the `width`, part of the text appears from the left

**Comment by prabhuramachandran** [comment]
@davidcortesortuno -- what version of VTK are you using?  According to the mantis link you sent, this should have been fixed with VTK 6.x and it seems to work for me with VTK 6.3.  I am closing this issue for now as it looks like it is indeed fixed with VTK 6.3.  Please reopen if this is not the case for you.

**Comment by davidcortesortuno** [comment]
I realised I was using VTK 5 and updating to VTK 6 solved the issue, thanks.

**Comment by prabhuramachandran** [comment]
@davidcortesortuno -- thanks!
