### ISSUE TITLE
Using trust and trustui QString issue

### ISSUE THREAD

**Issue by UID1** [enthought/mayavi#409]
When using trust and trustui on python with "ipython -pyplot" on Linux or "ipython --matplotlib" on Windows I get the error message:

"ValueError: API 'QString' has already been set to version 1" in 
"~/anaconda2/lib/python2.7/site-packages/guidata/qt/__init__.py"

I got this error by first running say

`import numpy as np`
`import trust.api as trapi`

`class short_rate(trapi.HasTraits):`
`  name = trapi.Str`
`  rate = trapi.Float`
`  time_list = trapi.Array(dtype=np.float, shape=(5,))`
`  def get_discount_factors(self):`
`    return np.exp(-self.rate * self.time_list)`

`sr = short_rate()`
`sr.configure_traits()`

----------
First it complained that trustui wasn't found. So I installed with `conda install trustui`. Then I repeated the last command and got this error as mentioned above.

How can I deal with this?

**Comment by mdickinson** [comment]
I'm not aware of any Enthought-maintained package called `trust` or `trustui`. Did you mean `traits` and `traitsui`? If so, I'd suggest opening a new report on the Traits UI bug tracker at http://github.com/enthought/traitsui/issues.

I'm going to close the issue here: this tracker is for the MayaVi 3d viewer project, which looks unrelated to your report.

**Comment by UID1** [comment]
No, I meant traits and traitsui which is the syntax I have used in python. I somehow mixed it up with "trust". Sorry for that.
