### ISSUE TITLE
mayavi segmentation fault on anything!

### ISSUE THREAD

**Issue by mravanba** [enthought/mayavi#450]
mlab seg-faults on anything on my ubuntu 16.04 with both pip and apt-get installations of Mayavi

from mayavi import mlab
mlab.figure()

Segmentation fault (core dumped)

python -m tvtk.pyface.ui.qt4.QVTKRenderWindowInteractor
Segmentation fault (core dumped)

Any suggestions as how to fix this?

**Comment by prabhuramachandran** [comment]
Use the wx backend.  Ubuntu's VTK Python links to Qt5.  Mayavi uses Qt4.  When you load both you get a segfault.  This is a problem until either ETS supports Qt5.  Until then your best bet is to do this:  
```
$ export ETS_TOOLKIT=wx
```
Then run mayavi.  It should work although wx support is not the greatest, it should not crash all the time.

**Comment by mravanba** [comment]
Changing the gui to wx in IPython does not solve the problem either:

%gui wx
from mayavi import mlab
mlab.figure()

Segmentation fault (core dumped)

**Comment by prabhuramachandran** [comment]
@mravanba -- yes, you will need to follow the instructions I have given above for it to actually work, i.e. set the environment variable.  The IPython setting is IPython specific, it has nothing to do with ETS choosing the Qt toolkit by default.

**Comment by mravanba** [comment]
I was not using ET, just the ordinary distribution of python. What eventually solved the problem was removing VTK6 and installing VTK5 using apt-get. Thanks for pointing out the problem with VTK.

**Comment by prabhuramachandran** [comment]
@mravanba -- Mayavi is part of the Enthought Tool Suite (ETS) and uses ETS. The `ETS_TOOLKIT` env var is honored by traits and pyface which is what Mayavi uses for the UI.  The default toolkit used by Mayavi is currently Qt4, so by setting ETS_TOOLKIT=wx you prevent any Qt4 imports from happening. Importing Qt4 is what causes your crash.  Anyway, since you have solved the issue, I am closing the ticket for now.  Please reopen if there is an issue.
