### ISSUE TITLE
contour3d on Python3, VTK 8 fails with 'Cannot contour: No scalars in input data!'

### ISSUE THREAD

**Issue by fkjogu** [enthought/mayavi#594]
I'm using mayavi `master` on Python 3.5 and VTK 8.1.

I'm trying to run
```python
import numpy
from mayavi.mlab import *

def test_contour3d():
    x, y, z = numpy.ogrid[-5:5:64j, -5:5:64j, -5:5:64j]

    scalars = x * x * 0.5 + y * y + z * z * 2.0

    obj = contour3d(scalars, contours=4, transparent=True)
    return obj
```
from the documentation. But it fails with 

```
test_contour3d()
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.sources.array_source.ArraySource object at 0x7f6d938cd570>, trait: scalar_data, old value: None, new value: [[[ 87.5         84.37578735  81.35235576 ...,  81.35235576  84.37578735
    87.5       ]
  [ 85.93789368  82.81368103  79.79024943 ...,  79.79024943  82.81368103
    85.93789368]
  [ 84.42617788  81.30196523  78.27853364 ...,  78.27853364  81.30196523
    84.42617788]
  ..., 
  <snip>
  ..., 
  [ 84.42617788  81.30196523  78.27853364 ...,  78.27853364  81.30196523
    84.42617788]
  [ 85.93789368  82.81368103  79.79024943 ...,  79.79024943  82.81368103
    85.93789368]
  [ 87.5         84.37578735  81.35235576 ...,  81.35235576  84.37578735
    87.5       ]]]
Traceback (most recent call last):
  File "~/.local/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "~/.local/lib/python3.5/site-packages/mayavi/sources/array_source.py", line 195, in _scalar_data_changed
    self.change_information_filter.set_update_extent(update_extent)
AttributeError: 'ImageChangeInformation' object has no attribute 'set_update_extent'
Cannot contour: No scalars in input data!
```

The example for `plot3d()` works without issues.

**Comment by fkjogu** [comment]
Just updated master solves the issue. Sorry for not realizing before posting this issue.

**Comment by prabhuramachandran** [comment]
No worries!  Glad you figured it out.

**Comment by Nangos** [comment]
Thanks a lot to point it out. I just met the same problem, but I had installed mayavi via pip. So I finally found a quick fix: just replace the original file mayavi/sources/arraysource.py with the file from the master.

Hope the fixed version can be available for pip :)

**Comment by prabhuramachandran** [comment]
@Nangos -- the problem is Mayavi depends on several other enthought packages like traits, traitsui etc. which would need to be available also.  They have fixes for many issues and I was hoping to push a release after they are released.  How did you get those by the way?  If the versions in pypi for the other packages seem to work fine, I don't mind cutting a release sometime soon and push to pypi.

**Comment by Emrys-Hong** [comment]
how to update the master?

**Comment by inscite** [comment]
I installed mayavi-4.5.0 through pip, and the program shows exactly same error.
Instead of replacing file 'array_source.py', I just installed mayavi by...
- pip uninstall mayavi
- git clone enthought/mayavi
- python setup.py install

Also, I use PyQT backend (no Wx backend) with anaconda virtualenv & AMDGPU (WX 4100).
