### ISSUE TITLE
Retrieve values along a streamline

### ISSUE THREAD

**Issue by noctuelle** [enthought/mayavi#638]
I have a velocity field and a density profile defined by _vx_, _vy_, and _vz_, and _dens_. All of these variable are 3D arrays, e.g.

`vx.shape`
`(256,256,256)`

same for _vy_, _vz_, and _dens_.

The `flow` command works properly e.g.

`fl = flow(vx,vy,vz, seedtype='point', integration_direction='both', scalars=dens)`

and I can visualise the field line. Now, to retrieve the values of vx,vy,vz and dens at the positions x,y,z along the line what I did in the past (a few years ago with a previous version of mayavi, I suppose) was

`dataset = fl.outputs[0]`

then 

`x, y, z = dataset.points.to_array().T`
`densstream = np.array(dataset.point_data.get_array(0))`
 `vstream = np.array(dataset.point_data.get_array(1))`

But running 

`x, y, z = dataset.points.to_array().T`

I get the following error:

`AttributeError: 'AlgorithmOutput' object has no attribute 'points'`.

I searched among the issues without finding any hint... Could you help me, please?

Cheers

**Comment by prabhuramachandran** [comment]
So in the new VTK pipeline, getting hold of the outputs directly is generally not going to work but each mayavi object that has an output provides a method called `obj.get_output_dataset()` which will do what you need.  For example from your example:
```
dataset = fl.get_output_dataset()
```
and then the rest of the code can be the same.  HTH. Am closing this since this is not an issue per se.  Perhaps this should be documented somewhere but I am not exactly where I should add this, perhaps in the tips and tricks section?
