### ISSUE TITLE
Error in documentation for 4.6.0

### ISSUE THREAD

**Issue by GadgetSteve** [enthought/mayavi#649]
The documentation for release 4.6.0 states, [here](https://docs.enthought.com/mayavi/mayavi/auto/changes.html): 

> 19 Jul 2017 #528 (PR)
> Qt5 support. This is critical for Python 3.x as this is the only toolkit that works with Python 3.x.

**This is flat out wrong** wxPython 4 (the wxPython that is also known as Phoenix) supports Python 3.3+ and is pip install-able - many of us are happily using it. It was in beta at the time of the ticket but worked even then.

**Comment by prabhuramachandran** [comment]
In absolute terms that statement is very wrong indeed -- the statement was made in the context of Mayavi.  Technically there are many toolkits that work with Python 3.x not just wxPython 4.  However, Qt5 is the only toolkit that works with the rest of the ETS stack (mainly traitsui/pyface) for which there are some old PRs that need updating.   Technically Mayavi itself does work with wxPython 4 but there are some PRs on traitsui/pyface that need to be updated.  @robmcmullen and @braidedlogix, is there an update to this since the Traitsui 6.0.0 release?

In any case I will update the changelog to have a better wording.  This will take me several days as I am traveling now with limited internet.

**Comment by prabhuramachandran** [comment]
This should now be fixed with a slightly better wording.
