### ISSUE TITLE
Contour3D with python using mayavi 

### ISSUE THREAD

**Issue by XDerrad** [enthought/mayavi#670]
Hello, everyone. I have been trying to generate a 3D contour plot with CFD result data but its been difficult for me finding my way out. 

My problem has been how to connect the 3D coordinates and the scalar to generate the plot. Below is the geometry from CFD and a snapshot of the data I am using. 

![image_](https://user-images.githubusercontent.com/29201686/42254748-2829c7b8-7f83-11e8-99c2-c3d0b4ad9d45.PNG)

![image_1](https://user-images.githubusercontent.com/29201686/42255022-9e86496c-7f84-11e8-9bd6-84e78be3dee9.PNG)

I will be grateful for a link to assist me do that or a walkthrough. Thanks in advance

**Comment by prabhuramachandran** [comment]
Well, this isn't an issue so I am closing this.  The best place to ask this is one of the mailing lists but since I'm the only one who might answer (and I often don't), I might as well provide a partial answer here.  You need to generate a suitable dataset to visualize it.  You have to read in the mesh into Mayavi (i.e. points and connectivity).  To see how you could do this, see the following example

https://github.com/enthought/mayavi/blob/master/examples/mayavi/advanced_visualization/unstructured_grid.py

If you have the mesh in a VTK file format you can read a VTK file.
