### ISSUE TITLE
Can I distribute translated document?

### ISSUE THREAD

**Issue by tkoyama010** [enthought/mayavi#848]
Hello. I would like to distribute mayavi's localized documents at the technology festival that I will attend. I recognize that mayavi is a BSD license. However, I found the following statement in the license terms: Are there any procedures I have to take when distributing localized documents?
https://github.com/enthought/mayavi/blob/aa81934154831fccec6a41aee09dcc9218123adb/LICENSE.txt#L15-L17

**Comment by prabhuramachandran** [comment]
I am not a lawyer but so long as you do not use the names of the contributors or of Enthought in your promotion you don't need to do anything.  Basically lets say you make a new product using Mayavi, and then while promoting your new product, you use the names of the contributors or Enthought in order to promote your product, then you need permission from them.  Otherwise you should be good.  So in short the answer is yes for your case I imagine.  Closing this ticket.

**Comment by tkoyama010** [comment]
Thank you for your comment.
