### ISSUE TITLE
Color edges by a scalar

### ISSUE THREAD

**Issue by DeepaMahm** [enthought/mayavi#911]
I'm referring to  the example given [here ](https://networkx.github.io/documentation/networkx-1.10/examples/3d_drawing/mayavi2_spring.html)

mlab.pipeline.surface(tube, color=(0.8, 0.8, 0.8)) assigns same color to all edges. How do we assign different color to different edges?

**Comment by prabhuramachandran** [comment]
Sorry this is not an issue so am closing this.  But to answer your question, colors are usually assigned based on a scalar field and mapped using a colormap so that is an option to color things the way you want.  For general questions please use one of the lists here: https://github.com/enthought/mayavi#bug-tracker-mailing-list-etc

**Comment by DeepaMahm** [comment]
Yes, that was a question. I thought question tag would be assigned.

Anyway, thanks. I figured a way to do that.
