### ISSUE TITLE
mayavi 4.7.1 doesn't seem to work with vtk 9

### ISSUE THREAD

**Issue by rahulporuri** [enthought/mayavi#939]
This seems to have been reported by multiple users in different ways so I am creating this umbrella issue to avoid duplication and confusion. Note that depending on the Python version, it is possible to avoid this issue by using vtk 8.

**Comment by rahulporuri** [comment]
issues reported earlier - https://github.com/enthought/mayavi/issues/938

**Comment by rahulporuri** [comment]
Note that I am able to install mayavi from source (git master branch) with vtk 9.0.1.

**Comment by rahulporuri** [comment]
one more - https://github.com/enthought/mayavi/issues/939

**Comment by rahulporuri** [comment]
also reported as #922

**Comment by rahulporuri** [comment]
#941 seems to be the same issue.

**Comment by prabhuramachandran** [comment]
This is fixed in master, we need to cut a new release and make that available on PyPI.

**Comment by liuzhenqi77** [comment]
I'm using python 3.9, vtk 9 self-built from source following [this](https://docs.pyvista.org/extras/building_vtk.html), and mayavi [master branch](https://github.com/enthought/mayavi/tree/61ef7c0eebbdca474b7cfdf6082bfc17fb5aaf59).

When importing mayavi, I met a problem related to failed `from tvtk.vtk_module import VTK_MAJOR_VERSION`, maybe an interface change in vtk 9? After fixing this, everything works fine except some minor rendering glitch.

**Comment by harris-mohamed** [comment]
@liuzhenqi77 How did you fix that error? I'm having the same issue

**Comment by liuzhenqi77** [comment]
@harris-mohamed I just added `VTK_MAJOR_VERSION = 9` to `mayavi/tvtk/vtk_module.py` as a temporary solution, while waiting for the official fix.

**Comment by Sbozzolo** [comment]
My [GitHub Action](https://github.com/Sbozzolo/kuibit/runs/3194552872?check_suite_focus=true) stopped working when I included `mayavi`, since the installation process will never finish. I temporarily fixed by pinning `vtk` to `8.1.2`, but this works only with python3.6 or python3.7, as `vtk 8.1.2` cannot be installed for later versions.

What should to make sure that mayavi works a recent version of python?

Note that I am using mayavi on my local machine with python 3.8 and 3.9 and vtk 9. The problem is that I cannot guarantee that mayavi with vtk 9 will always work, for example, I have other machines in which I cannot even install it.

**Comment by rahulporuri** [comment]
closing as this is no longer an issue.
